### ISSUE TITLE
Very high memory usage

### ISSUE THREAD

**Issue by supsm** [Johni0702/bobby#17]
Minecraft frequently crashes due to out of memory errors. I've allocated 4 GB of ram to mc, and without bobby this does not happen nearly as frequently. 

Unfortunately it is not in logs, but in MultiMC console it said unable to allocate 1 GB of memory for chunk::new or something like that.

Here are some logs anyway:

[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 14/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 2/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 11/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 10/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: java.lang.OutOfMemoryError
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.nmemAllocChecked(MemoryUtil.java:247)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at org.lwjgl.system.MemoryUtil.memAlloc(MemoryUtil.java:271)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.buffer.TransferBufferAllocator.claim(TransferBufferAllocator.java:54)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.buffer.VboBuffer.<init>(VboBuffer.java:48)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.terrain.render.UploadableChunk.<init>(UploadableChunk.java:34)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.buffer.encoding.VertexCollectorList.toUploadableChunk(VertexCollectorList.java:123)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.terrain.region.BuiltRenderRegion.rebuildOnWorkerThread(BuiltRenderRegion.java:486)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at grondag.canvas.terrain.util.TerrainExecutor$Worker.run(TerrainExecutor.java:116)
[13:19:18] [Canvas Render Thread - 3/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by supsm** [comment]
Actually, I'm not sure if this is bobby's issue. I'll close this for now.
