### ISSUE TITLE
incompatible with sodium 0.5

### ISSUE THREAD

**Issue by Oguzhan5585** [Johni0702/bobby#197]
game crashes with sodium 0.5 and latest bobby

**Comment by zz13254235** [comment]
Time: 2023-08-05 09:03:28
Description: Unexpected error

java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(int, int)'
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at de.johni0702.minecraft.bobby.sodium.BufferedChunkStatusListener.onChunkAdded(BufferedChunkStatusListener.java:18)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zzc000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Seba244c** [comment]
Same error
`java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(int, int)'
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zlc000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)`

**Comment by alien-sunset** [comment]
same
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2023-08-05 18:14:00
Description: Unexpected error

java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(int, int)'
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at de.johni0702.minecraft.bobby.sodium.BufferedChunkStatusListener.onChunkAdded(BufferedChunkStatusListener.java:18)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zeg000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.johni0702.minecraft.bobby.sodium.SodiumChunkStatusListenerImpl.onChunkAdded(SodiumChunkStatusListenerImpl.java:10)
	at de.johni0702.minecraft.bobby.sodium.BufferedChunkStatusListener.onChunkAdded(BufferedChunkStatusListener.java:18)
	at net.minecraft.class_631.bobby_onFakeChunkAdded(class_631.java:2022)
	at net.minecraft.class_631.handler$zeg000$bobby$bobbyPostLoadRealChunk(class_631.java:597)
	at net.minecraft.class_631.method_16020(class_631.java:123)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['Alien_Sunset'/547880, l='ClientLevel', x=-324.48, y=83.56, z=-568.03]]
	Chunk stats: 4096, 1 F: 0 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (-111,96,-131), Section: (at 1,0,13 in -7,6,-9; chunk contains blocks -112,-64,-144 to -97,319,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 38283781 game time, 25830995 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Classic Faithful 32x Jappa - 1.20.zip, file/pridepack5.0.zip, file/Directional Observers.zip, file/Directional Utilities.zip, file/Faithful-Java-32x-Visual_Banner_Patterns_v1.0.zip, file/Sticky Piston Sides.zip, file/Inconsistency Fixes.zip, file/Rainbow XP Bar 32x (1).zip, file/nicer-fast-leaves-32.zip, file/VanillaTweaksx32.zip, file/Emissive Textures.zip, file/homebrew custom textures.zip, file/rotated-nature.zip, file/visible-glint-v1-1.zip, file/visible-powder-snow.zip, betterbeds:connectedbeds, file/Dramatic+Skys+Demo+1.5.3.10 colorfix.zip, continuity:default, continuity:glass_pane_culling_fix, file/Fast Better Grass.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 484319232 bytes (461 MiB) / 1707081728 bytes (1628 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 4600
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x0416
	Graphics card #0 versionInfo: DriverVersion=20.19.15.5126
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 18713.11
	Virtual memory used (MB): 9143.02
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 85.20
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.1.12
		betterbeds: Better Beds 1.3.0
		bobby: Bobby 5.0.0
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.3+1.20.1
		deathlog: DeathLog 0.3.2+1.20
		detailab: Detail Armor Bar 2.6.3+1.20.1-fabric
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.8+kotlin.1.9.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.2+mc1.20.1
		ferritecore: FerriteCore 6.0.0
		flowermap: Flower Map 1.3.0
		hatlist: Hat List 1.5
		immediatelyfast: ImmediatelyFast 1.1.25+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.23+mc1.20.1
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.5
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller 0.20.0
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 3.0.2
		litematica: Litematica 0.15.3
		lithium: Lithium 0.11.2
		malilib: MaLiLib 0.16.1
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		minihud: MiniHUD 0.27.0
		modmenu: Mod Menu 7.2.1
		morechathistory: MoreChatHistory 1.1.1
		owo: oωo 0.11.1+1.20
			blue_endless_jankson: jankson 1.2.2
		petowner: Pet Owner 1.8.5-1.19.4+
			midnightlib: MidnightLib 1.2.1
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.20.1-build.94
		replaymod: Replay Mod 1.20.1-2.6.13
		roughlyenoughitems: Roughly Enough Items 12.0.634
			error_notifier: Error Notifier 1.0.9
		skinswapper: Skin Swapper 3.1.4
			org_apache_httpcomponents_httpclient: httpclient 4.5.10
			org_apache_httpcomponents_httpcore: httpcore 4.4.12
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		sodium: Sodium 0.5.0
		sodium-extra: Sodium Extra 0.5.0+mc1.20.1-build.111
			caffeineconfig: CaffeineConfig 1.3.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		status: Status 1.20.1-1.0.4
		symbol-chat: Symbol Chat 1.20.1-1.1.0
		tweakeroo: Tweakeroo 0.17.1
		xaerominimap: Xaero's Minimap 23.6.0
		xaeroworldmap: Xaero's World Map 1.31.0
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) HD Graphics 4600 GL version 3.2.0 - Build 20.19.15.5126, Intel
	Window size: 1366x705
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/Classic Faithful 32x Jappa - 1.20.zip (incompatible), file/pridepack5.0.zip, file/Directional Observers.zip, file/Directional Utilities.zip, file/Faithful-Java-32x-Visual_Banner_Patterns_v1.0.zip, file/Sticky Piston Sides.zip, file/Inconsistency Fixes.zip, file/Rainbow XP Bar 32x (1).zip, file/nicer-fast-leaves-32.zip, file/VanillaTweaksx32.zip, file/Emissive Textures.zip, file/homebrew custom textures.zip, file/rotated-nature.zip, file/visible-glint-v1-1.zip, file/visible-powder-snow.zip, betterbeds:connectedbeds (incompatible), file/Dramatic+Skys+Demo+1.5.3.10 colorfix.zip, continuity:default, continuity:glass_pane_culling_fix, file/Fast Better Grass.zip
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i5-4300M CPU @ 2.60GHz

**Comment by BuggyAl** [comment]
Here is the commit that deleted the method: https://github.com/CaffeineMC/sodium-fabric/commit/fb1eb2e70b7ce557508d0af934b2b291263464a0

**Comment by davepusey** [comment]
Getting the same issue here too when trying to update to Sodium 0.5 for Iris 1.6.5

**Comment by ryleu** [comment]
0.5.0 was a massive rework, so I would just roll back the sodium version for now.

**Comment by noah1510** [comment]
I looked into the bobby code. This does not seem trivial to fix. Basically all parts of the sodium compatibility have to be rewritten including the mixins. The most easy solution is probably to reimplement the on_chunk_added functions in the mixins and rely on that for the rest.

That being said, I am not familier with the chunk loading code, bobby or sodium. Someone who knows more about these code bases might have a better solution.

**Comment by davepusey** [comment]
Does this perhaps need reporting to the Sodium devs to get the on_chunk_added function reinstated?

**Comment by noah1510** [comment]
I just opened a pr with my temporary solutions. I didn't implement the lighting and could not test on a server. Can somebody test if this actually works or if this just gets rid of the errors?

**Comment by davepusey** [comment]
I'd be willing to try it if you can provide a built .jar file?

**Comment by Riprian** [comment]
> I just opened a pr with my temporary solutions. I didn't implement the lighting and could not test on a server. Can somebody test if this actually works or if this just gets rid of the errors?

It seems to just get rid of the errors. I built it from your fork directly.
[bobby-5.0.0.zip](https://github.com/Johni0702/bobby/files/12282515/bobby-5.0.0.zip)

**Comment by Tom1817** [comment]
have just tested your .jar - ty for compiling :) can confirm that it does get rid of the errors but does not load any extra chunks or do anything whatsoever

**Comment by davepusey** [comment]
No more errors, but render distance very limited to only 8 chunks radius now.

**Comment by noah1510** [comment]
[libs.zip](https://github.com/Johni0702/bobby/files/12284104/libs.zip)

here is the updated code. I messed up the call to the mixin functions. The latest state of the fork has it.
At the moment there might be lighting problems since the onChunkLightAdded function is just a dummy.

Can someone verify if this actually increases the render distance on servers, now that the function is called?

**Comment by Tom1817** [comment]
Are you able to compile it? then I can test

**Comment by noah1510** [comment]
I shared a zip with the compiled mod in my comment

**Comment by Riprian** [comment]
well it seems to kinda work now. but whenever I look away it unloads the chunks and reloads them when I look at these chunks.

**Comment by noah1510** [comment]
I think that is an optimization in sodium. Getting sodium 0.5.0 to fully work will take a lot of work.

**Comment by davepusey** [comment]
> 

Yeah, that seems to have fixed it. Many thanks for your efforts in getting this resolved and updated so quickly.

**Comment by noah1510** [comment]
I did some more changes and implementing suggestions from the pr.
[This file](https://github.com/Johni0702/bobby/files/12292722/bobby_5.1_dev.zip) is the latest state.
I added compatibility with both sodium 0.5 and 0.4.

Due to the flickering of chunks being reloaded I still recommend using sodium 0.4 but with that update both work so use what you want.

**Comment by EGOIST1372** [comment]
@noah1510 Hey there
It would be great if you could make a build for each change in your repo in action tab so people can download it as artifact.jar

**Comment by noah1510** [comment]
While I don't mind setting up a ci file, I don't see the benefit.
I uploaded updated version for each relevant change.
The reason I didn't upload for the latest commit, was because it only contained internal changes but the called functions were the same.
Since this didn't change anything about the mod, I don't feel the need to provide an updated binary.

If it is really needed I can set it up, but I think just manually uploading the latest binary should be the better option, since I have to compile it myself anyway and don't need to use CI resources that could be used for more important projects.

**Comment by noah1510** [comment]
You can find the latest file in my most recent comment in #199.

**Comment by SALTWOOD** [comment]
same error
here's the crash report
[错误报告-2023-8-11_1.04.58.zip](https://github.com/Johni0702/bobby/files/12315709/-2023-8-11_1.04.58.zip)

**Comment by noah1510** [comment]
I think the error you get is because you use quilt.
Try reproducing the error with less mods, you have too many mods to isolate the problem.

**Comment by davepusey** [comment]
It's the same error message, and they have Sodium 0.5 installed.

**Comment by EGOIST1372** [comment]
Ive tested it with sodium 0.5.0 and all the sodium related mods
Works pretty good
Thanks so much

**Comment by noah1510** [comment]
As mentioned in the PR there is one fix from sodium that is needed, once that is done and they released v0.5.1, bobby should work without glitches again.
The current fix gets everything working just with a few graphical bugs.

**Comment by noah1510** [comment]
I just posted an updated build in the PR.
It contains a fix to the most noticeable rendering problem.
The chunk flickering is gone now, but there are still some minor problems that need fixing.

**Comment by Johni0702** [comment]
https://github.com/Johni0702/bobby/releases/tag/v5.0.1
https://modrinth.com/mod/bobby/version/5.0.1
https://www.curseforge.com/minecraft/mc-mods/bobby/files/4706163

**Comment by ST-DDT** [comment]
Note: Sodium v0.5.1 has still some bugs that might cause issues with other mods. Those will supposedly be fixed in Sodium v0.5.2
(e.g. NoFog is also affected)
