### ISSUE TITLE
IndexOutOfBoundsException on FakeChunkStorage

### ISSUE THREAD

**Issue by breadbyte** [Johni0702/bobby#27]
Whenever I try and join a server, I see a lot of these errors on my client (1.17):
https://gist.github.com/breadbyte/cd5a467ceeb21c136b971350530be0a1

The line referenced is https://github.com/Johni0702/bobby/blob/master/src/main/java/de/johni0702/minecraft/bobby/FakeChunkStorage.java#L204

As a workaround I tried deleting `.bobby`, but to no avail.

**Comment by Johni0702** [comment]
Is it a vanilla server? Is it public so I could join myself?
Which dimension is this in? Does it use the experimental tall worlds data pack?
Do you get the same issue in single player?
Any other mods?

**Comment by breadbyte** [comment]
Hi! Thanks for the questions.

I am playing on a private Spigot server, and the dimension is overworld.
For reference, my bobby version is https://github.com/Johni0702/bobby/releases/tag/v2.0.0

I did some testing myself, and got the following outcome:
I can reproduce the issue with a fresh copy of Spigot, without any datapacks or plugins.
Could not replicate on singleplayer.
Could not replicate on a Fabric server.

I can reproduce the issue with only these mods loaded alongside bobby:
- Cloth API
- Cloth Config
- Fabric API
- Mod Menu

If you would like more information or world copies, please let me know. Thanks for this awesome mod!

**Comment by magneticflux-** [comment]
I'm getting the same error, the server render distance is 16 and the client's is 32.
The server is Fabric and isn't using tall worlds.
```
[18:42:30] [Render thread/FATAL]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: Index 16 out of bounds for length 16
	at de.johni0702.minecraft.bobby.FakeChunkStorage.deserialize(FakeChunkStorage.java:204) ~[bobby-2.0.0.jar:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:280) ~[bobby-2.0.0.jar:?]
	at net.minecraft.class_631.handler$cij000$bobbyReplaceChunk(class_631.java:1647) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_631.method_2859(class_631.java:66) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_634.method_11107(class_634.java:689) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_2666.method_11486(class_2666.java:28) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_2666.method_11054(class_2666.java:6) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1077) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

Mod list:
```
[18:41:21] [main/INFO]: [FabricLoader] Loading 141 mods:
	- advanced_runtime_resource_pack@0.4.3
	- advancements-enlarger@0.2.4
	- architectury@2.0.14
	- autoconfig1u@3.3.1
	- beaconsforall@2.0.0-1.17
	- betterrsqrt@1.0.1
	- betterthanmending@1.3.0
	- blame@1.17-4.0.0-fabric
	- blue_endless_jankson@1.2.1
	- bobby@2.0.0
	- carpet@1.4.40
	- carpet-extra@1.4.40
	- cloth-api@2.0.54
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.34
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- com_github_shevek_parallelgzip@master-SNAPSHOT
	- com_moandjiezana_toml_toml4j@0.7.2
	- com_skaggsm_java-mumble-link@0.2.6
	- com_skaggsm_jvm-shared-memory@0.2.7
	- com_typesafe_config@1.4.1
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- confabricate@2.1.0-SNAPSHOT+4.1.1
	- cotton-config@1.0.0-rc.7
	- cotton-logging@1.0.0-rc.4
	- dynamicfps@2.0.4
	- entityculling@1.3.0
	- fabric@0.36.0+1.17
	- fabric-api-base@0.3.0+a02b4463d5
	- fabric-api-lookup-api-v1@1.2.0+2b5c62d03d
	- fabric-biome-api-v1@3.1.11+c345aea83d
	- fabric-blockrenderlayer-v1@1.1.5+a02b44633d
	- fabric-command-api-v1@1.1.1+a02b4463d5
	- fabric-commands-v0@0.2.2+92519afa3d
	- fabric-containers-v0@0.1.12+a02b44633d
	- fabric-content-registries-v0@0.2.2+a02b44633d
	- fabric-crash-report-info-v1@0.1.5+be9da3103d
	- fabric-diagonal-panes@0.5.0
	- fabric-dimensions-v1@2.0.10+a02b44633d
	- fabric-entity-events-v1@1.1.0+a02b44633d
	- fabric-events-interaction-v0@0.4.9+a722d8c03d
	- fabric-events-lifecycle-v0@0.2.1+92519afa3d
	- fabric-game-rule-api-v1@1.0.6+a02b44633d
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab61213d
	- fabric-key-binding-api-v1@1.0.4+a02b44633d
	- fabric-keybindings-v0@0.2.2+36b77c3e3d
	- fabric-language-kotlin@1.6.1+kotlin.1.5.10
	- fabric-lifecycle-events-v1@1.4.4+a02b4463d5
	- fabric-loot-tables-v1@1.0.4+a02b44633d
	- fabric-mining-levels-v0@0.1.3+92519afa3d
	- fabric-models-v0@0.3.0+a02b44633d
	- fabric-mumblelink-mod@0.8.3
	- fabric-networking-api-v1@1.0.11+b7ab6121d5
	- fabric-networking-blockentity-v0@0.2.11+a02b44633d
	- fabric-networking-v0@0.3.2+92519afa3d
	- fabric-object-builder-api-v1@1.10.9+b7ab61213d
	- fabric-object-builders-v0@0.7.3+a02b44633d
	- fabric-particles-v1@0.2.4+a02b44633d
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee3d
	- fabric-renderer-api-v1@0.4.3+676f40fa3d
	- fabric-renderer-indigo@0.4.8+a02b44633d
	- fabric-renderer-registries-v1@3.2.0+a02b44633d
	- fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
	- fabric-rendering-fluids-v1@0.1.13+a02b44633d
	- fabric-rendering-v0@1.1.2+92519afa3d
	- fabric-rendering-v1@1.6.0+a02b44633d
	- fabric-resource-loader-v0@0.4.7+b7ab61213d
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+a02b44633d
	- fabric-start-the-music@0.3.1
	- fabric-structure-api-v1@1.1.11+e36969833d
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b44633d
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-tree-chopper@0.7.0
	- fabricloader@0.11.6
	- fabrishot@1.5.0
	- fastchest@1.2+1.17
	- fiber@0.23.0-2
	- fiber2cloth@3.2.0
	- hologram-api@0.1.0-1.17
	- hydrogen@0.3-SNAPSHOT
	- indium@1.0.0+rev.341c70b
	- inventorysorter@1.7.9-1.17
	- io_leangen_geantyref_geantyref@1.3.11
	- jankson@3.0.0+j1.2.0
	- java@16
	- kirin@1.8.7-1.17
	- krypton@0.1.3
	- kyrptconfig@1.1.10-1.17
	- lambdabettergrass@1.2.0+1.17
	- lambdynlights@2.0.1+1.17
	- lazydfu@0.1.2
	- libzoomer@0.2.1+1.17
	- lithium@0.7.1-SNAPSHOT
	- minecraft@1.17
	- mm@2.1
	- modmenu@2.0.2
	- mostructures@1.2.0-1.17
	- okzoomer@5.0.0-beta.2+1.17
	- omega-config@1.0.8
	- org_apache_commons_commons-compress@1.19
	- org_aperlambda_lambdajcommon@1.8.1
	- org_codehaus_groovy_groovy@3.0.8
	- org_codehaus_groovy_groovy-jsr223@3.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
	- org_spongepowered_configurate-core@4.1.1
	- org_spongepowered_configurate-extra-dfu4@4.1.1
	- org_spongepowered_configurate-gson@4.1.1
	- org_spongepowered_configurate-hocon@4.1.1
	- org_tukaani_xz@1.8
	- packet_tweaker@0.2.0-1.17-pre1
	- placeholder-api@1.0.0-rc2-1.17
	- polymer@0.1.0-pre5-1.17
	- presencefootsteps@r31-1.17-rc1
	- repurposed_structures@2.0.0+1.17.0
	- roughlyenoughitems@6.0.258-alpha
	- server_translations_api@1.4.5+1.17
	- sgui@1.0.0-rc2-1.17
	- slight-gui-modifications@2.0.0
	- sodium@0.3.0+rev.908510e
	- spruceui@3.2.0+1.17
	- textile_backup@2.1.0-1.17
	- the_loved_ones@1.2.0+1.17
	- universal-graves@1.0.2
	- worldedit@7.3.0-SNAPSHOT+5836-183ae4a
	- worldeditcui@1.17-pre2+01-SNAPSHOT
	- wthit@3.6.1
```
