### ISSUE TITLE
Multiplayer only crash.

### ISSUE THREAD

**Issue by RDKRACZ** [Johni0702/bobby#32]
```
[18:19:48] [Render thread/FATAL]: Unreported exception thrown!
java.lang.NoClassDefFoundError: net/minecraft/class_4298
	at de.johni0702.minecraft.bobby.FakeChunkStorage.deserialize(FakeChunkStorage.java:251) ~[bobby-2.0.2.jar:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:260) ~[bobby-2.0.2.jar:?]
	at net.minecraft.class_631.substituteFakeChunksForUnloadedRealOnes(class_631.java:1117) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_631.handler$zcm000$bobbySubstituteFakeChunksForUnloadedRealOnes(class_631.java:1155) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_631.method_2859(class_631.java:66) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_634.method_11107(class_634.java:690) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2666.method_11486(class_2666.java:28) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2666.method_11054(class_2666.java:6) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1075) ~[intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:728) [intermediary-minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4298
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 31 more
[18:19:48] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Rendering Data Attachment (v1), Fabric Resource Loader (v0), Mod Menu, Fabric Loader, Fabric Rendering Fluids (v1), Fabric Screen API (v1), Sodium, Bobby, Fabric API Base)
[18:19:48] [Render thread/INFO]: Stopping worker threads
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/6/21, 6:19 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: net/minecraft/class_4298
	at de.johni0702.minecraft.bobby.FakeChunkStorage.deserialize(FakeChunkStorage.java:251)
	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:260)
	at net.minecraft.class_631.substituteFakeChunksForUnloadedRealOnes(class_631.java:1117)
	at net.minecraft.class_631.handler$zcm000$bobbySubstituteFakeChunksForUnloadedRealOnes(class_631.java:1155)
	at net.minecraft.class_631.method_2859(class_631.java:66)
	at net.minecraft.class_634.method_11107(class_634.java:690)
	at net.minecraft.class_2666.method_11486(class_2666.java:28)
	at net.minecraft.class_2666.method_11054(class_2666.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.class_310.method_1523(class_310.java:1075)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4298
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 31 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at de.johni0702.minecraft.bobby.FakeChunkStorage.deserialize(FakeChunkStorage.java:251)
	at de.johni0702.minecraft.bobby.FakeChunkManager.load(FakeChunkManager.java:260)
	at net.minecraft.class_631.substituteFakeChunksForUnloadedRealOnes(class_631.java:1117)
	at net.minecraft.class_631.handler$zcm000$bobbySubstituteFakeChunksForUnloadedRealOnes(class_631.java:1155)
	at net.minecraft.class_631.method_2859(class_631.java:66)
	at net.minecraft.class_634.method_11107(class_634.java:690)
	at net.minecraft.class_2666.method_11486(class_2666.java:28)
	at net.minecraft.class_2666.method_11054(class_2666.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)

-- Affected level --
Details:
	All players: 3 total; [class_746['_K0RR_'/17762, l='ClientLevel', x=-157.91, y=128.74, z=1136.63], class_745['Naciacia'/368, l='ClientLevel', x=-124.62, y=67.00, z=1187.99], class_745['_Nikola_B_bn_'/18541, l='ClientLevel', x=-127.72, y=67.00, z=1191.22]]
	Chunk stats: 1024, 165 F: 0 L: 0 U: 130
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,66,176), Section: (at 0,2,0 in 3,4,11; chunk contains blocks 48,0,176 to 63,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5195295 game time, 32581 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, d159876ade6b41900300c4477177819318c969bc

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.11.0-18-generic
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1649081328 bytes (1572 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
	Identifier: Intel64 Family 6 Model 94 Stepping 3
	Microarchitecture: Skylake (Client)
	Frequency (GHz): 4.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: GP104 [GeForce GTX 1070]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x1b81
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 48797.27
	Virtual memory used (MB): 45412.98
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 15188.12
	JVM Flags: 2 total; -Xms4096m -Xmx4096m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 3.2.0 NVIDIA 460.80, NVIDIA Corporation
	Window size: 3402x1415
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/k0rr/.local/share/multimc/instances/21w07a/.minecraft/crash-reports/crash-2021-07-06_18.19.48-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

```

**Comment by RDKRACZ** [comment]
MC 1.17.1. Sodium 0.3. Starlight 1.0 RC3 (I know about the light issue)
I get this crash every time when I try to move on my server.

**Comment by Johni0702** [comment]
Bobby 2.0.2 is for Minecraft 1.17, not for 1.17.1, those two are not fully compatible.
