### ISSUE TITLE
Game freezes when joining world when its name has illegal characters

### ISSUE THREAD

**Issue by helpimnotdrowning** [Johni0702/bobby#67]
The game freezes (but doesn't crash) when I join a world with a name that has a special/illegal character.
With world name `TEST:`
```
[14:23:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:23:11] [Render thread/INFO]: Preparing spawn area: 0%
...
[14:24:04] [Render thread/INFO]: Preparing spawn area: 99%
[14:24:04] [Render thread/INFO]: Time elapsed: 54583 ms
[14:24:05] [Server thread/INFO]: Changing view distance to 128, from 10
[14:24:05] [Server thread/INFO]: Changing simulation distance to 128, from 0
[14:24:06] [Server thread/INFO]: iamdrowning[local:E:02688d2e] logged in with entity id 209 at (10.5, 70.0, 5.5)
[14:24:06] [Server thread/INFO]: iamdrowning joined the game
[14:24:07] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2700ms or 54 ticks behind
[14:24:08] [Render thread/FATAL]: Error executing task on Client
java.nio.file.InvalidPathException: Illegal char <:> at index 4: TEST:
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.nio.file.Path.resolve(Path.java:515) ~[?:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:99) ~[bobby-3.1.0.jar:?]
	at net.minecraft.class_631.handler$zzb000$bobbyInit(class_631.java:553) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.<init>(class_631.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
, and this makes the game vomit these errors untill I kill it:
```
[14:24:08] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_3146(String)" because "this.field_3690.field_1724" is null
	at net.minecraft.class_634.method_11152(class_634.java:1746) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	...
```
```
[14:24:08] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1657.method_31549()" because "$$1" is null
	at net.minecraft.class_634.method_11154(class_634.java:1551) ~[client-intermediary.jar:?]
	at net.minecraft.class_2696.method_11697(class_2696.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_2696.method_11054(class_2696.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	...
```
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1937.method_8469(int)" because "$$0" is null
	at net.minecraft.class_2663.method_11469(class_2663.java:38) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11148(class_634.java:887) ~[client-intermediary.jar:?]
	at net.minecraft.class_2663.method_11471(class_2663.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_2663.method_11054(class_2663.java:11) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	...
```
```[14:24:08] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_638.method_2935()" because "this.field_3699" is null
	at net.minecraft.class_634.method_20320(class_634.java:2233) ~[client-intermediary.jar:?]
	at net.minecraft.class_4282.method_20321(class_4282.java:28) ~[client-intermediary.jar:?]
	at net.minecraft.class_4282.method_11054(class_4282.java:6) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:110) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1080) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:733) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:238) [client-intermediary.jar:?]
	...
```

Originally, I thought this was due to loading amplified worlds untill I realized the world name `New World:AMP` had a colon, which isn't allowed in path names.

Running:
* Minecraft 1.18.1
* Fabric Loader 0.12.12
* Fabric API 0.44.0+1.18.1
* Bobby 3.1.0

**Comment by Johni0702** [comment]
Should finally be fixed as of Bobby 5.2.0.
